### PR TITLE
Fix background feck up

### PR DESCRIPTION
**Pull request by Rammahh**
Fixed the issue where 8bit mountain .png name was incorrect

### CODE REVIEW

**Comment by RammaOW** [comment]
https://github.com/avaire/avaire/pull/122 refer to

**Comment by Adyne** [comment]
Ur a feck up

**Comment by RammaOW** [comment]
Ok Cuck

**Comment by Adyne** [comment]
> 
> 
> Ok Cuck

**Comment by Macley-Kun** [comment]
Ok Cuck.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Meww#0001 <notifications@github.com>
Verzonden: zaterdag, oktober 12, 2019 5:26 PM
Aan: avaire/avaire
CC: Subscribed
Onderwerp: Re: [avaire/avaire] Fix background feck up (#121)


Ok Cuck

―

**Comment by RammaOW** [comment]
what kinda fucking reply is that nice email re4head

**Comment by Macley-Kun** [comment]
Download outlook for iOS. Cuck.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: RammaOW <notifications@github.com>
Verzonden: zaterdag, oktober 12, 2019 6:00 PM
Aan: avaire/avaire
CC: Macley; Comment
Onderwerp: Re: [avaire/avaire] Fix background feck up (#121)


what kinda fucking reply is that nice email re4head

**Comment by RammaOW** [comment]
No

**Comment by Macleykun** [comment]
Ok Cuck.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by RammaOW** [comment]
we're in the fucking discord why are we commenting and replying here lmaoo

**Pull request closed without merging**
