### PR TITLE
Hello My Noggerasrsr

### PR DESCRIPTION
**Pull request by WittiJ**
geagege

### CODE REVIEW

**Comment by a2937** [comment]
Dude stop. Like there's no need to have a pull request that accomplishes essentially nothing and hijacks the bot info. While I can understand wanting to use AvaIre as a base for your own Discord bot, don't just flat out hijack it and flood comments.

**Comment by Senither** [comment]
🤔 That's a really dumb pull request, maybe don't try to yoink the entire codebase, change all the sources to claim it as your own, and then try push those changes to the live bot, that's just idiotic.

**Comment by WittiJ** [comment]
I am very sorry my account got hacked i didnt want to do this :(

**Comment by Senither** [comment]
If it was a mistake I assume the fork of the project with all the changes that breaks the license was a part of the hack too then? If that's the case it would be very much appreciated if you could delete your fork as you're breaking the GPL license that the bot is registered under, rebranding the entire project as your own and claiming to be the original author isn't really cool. If you refuse to delete the fork and continue to use the modified code I'll just file a DMCA takedown for both the bot and the fork for breaking the license.

Cheers ❤️

**Pull request closed without merging**
