### PR TITLE
Improved Dockerization

### PR DESCRIPTION
**Pull request by sweepyoface**
This improves upon the original PR since it has gone inactive:
- Removes unnecessary steps
- Uses the official `openjdk:8-alpine` image
- Fixes the `config.yml` volume issue

Credit to #68 for the inspiration :+1:

### CODE REVIEW

**Comment by Macley-Kun** [comment]
Heya dude, saw in your pull that your using ` FROM gradle:jdk10-slim AS build`. But isn't it handier to use the same version for `FROM openjdk:8-alpine AS runtime`?
I do know that version 11 is also ok for avaire, it's actually something we want to update too when the dev announces a new mayor version.

I do like your pull, i wasn't aware that a dockfile could be so easily made!

**Comment by sweepyoface** [comment]
Because the `gradle:jdk8-alpine` image produces

```
/app/src/test/java/com/avairebot/utilities/NumberTests.java:25: error: package org.junit does not exist
import org.junit.Test;                                                                                                                                                             
                ^                                                                                                                                                                  
/app/src/test/java/com/avairebot/utilities/ArrayTests.java:25: error: cannot find symbol                                                                                           
import org.junit.Test;                                                                                                                                                             
                ^                                                                                                                                                                  
  symbol:   class Test                                                                                                                                                             
  location: package org.junit 

etc..
```

If that can be fixed, I'm happy to use JDK 8.

**Comment by Macley-Kun** [comment]
So, why not update openjdk:8-alpine to the newer openjdk10 then?
We rather move to using 11 (if possible for docker!) because of [it's LTS status](https://en.wikipedia.org/wiki/Java_version_history).
Refering to the other pull that is gonna be merged when a new version comes out: #64

**Comment by sweepyoface** [comment]
Ah, sorry, misread that. `openjdk:10-jdk-slim` does seem to work fine, though there is no Alpine image for some reason. Attempting to build on 11 causes the same issue as https://github.com/avaire/avaire/pull/95#issuecomment-502240387 for what it's worth.

**Comment by Macley-Kun** [comment]
Allrighty that is good 👍 i see why you would like to use alpine, it's alot smaller!
Hopefully Senither will have a look at it soon :-) thanks for your pull!

**Comment by Macley-Kun** [comment]
@sweepyoface i know this is a bit out of the blue. But would [this](https://github.com/docker-library/openjdk/blob/master/11/jdk/slim/Dockerfile) work to build it on java 11?

**Comment by Macley-Kun** [comment]
Also, if possible, could you show/test the following:
- [ ] That the bot compiles.
- [ ] Starts up correctly.
- [ ] Works with all the commands/features.
If that's all done, we can merge this pull 🎉

**Pull request closed without merging**
