### PR TITLE
Add fr_FR translation

### PR DESCRIPTION
**Pull request by braktar**
Hello,

I would like to push the french translation for a while. The @bafoulio issue remind me about it https://github.com/avaire/avaire/issues/10

Then here it is. Reviews are welcome, some translations seems a bit odd to me.

### CODE REVIEW

**Comment by bafoulio** [comment]
My english is very poor. ^^.

**Comment by bafoulio** [comment]
But cool, thank you.

**Comment by braktar** [comment]
I feel more confident with the current state of the translation

**Comment by Senither** [comment]
Looks nice 👍 There doesn't appear to be any formatting issues and every placeholder from the English file is used as well, so unless there is anything else you'd like to add I can merge the PR into the bot.

**Comment by bafoulio** [comment]
Yes. The french server we're happy.

**Comment by braktar** [comment]
If there is no yml file for the Chuck Norris facts, feel free to merge ;)

**Pull request merged**
