### PR TITLE
Add support for java 11

### PR DESCRIPTION
**Pull request by chaNcharge**
I've tested it on heroku, seems to work fine. I'd recommend updating to this as Java 11 is LTS.

### CODE REVIEW

**Comment by Macley-Kun** [comment]
image
I assume you've updated the gradle-wrapper.jar aswell...? XP

**Comment by chaNcharge** [comment]
Why are you downloading gradle 10.3? That doesn't even exist xD

**Comment by Macley-Kun** [comment]
Mmm weird that it somehow downloaded the right one...
But if you change the properties file, run gradle wrapper. It’ll change some files. You can try it out for yourself.

**Comment by chaNcharge** [comment]
Ok, I properly upgraded the wrapper and wrapper scripts, everything should work fine and be compatible with java 8-11

**Comment by Macley-Kun** [comment]
Looks good dude 👍 
@Senither want me to test this out on a fresh windows client?

**Comment by chaNcharge** [comment]
Ok, so for some reason, I literally have no idea why, but on Java 11 and the latest gradle 4.x version, on first build, I get this error: https://hastebin.com/oqoqevoxud. Rerunning the build once or twice resolves this issue. If you need to, we can hold off updating to Java 11 until this gets fixed.

**Comment by Macley-Kun** [comment]
Update time!

So funny thing, i have the following set:
java.runtime.version=11
Gradle = 4.10.3

And this is the build log: https://pastebin.com/9LTmrLU2

I don't have this issue to re-run it, and as this version isn't the 5 (what is quite a shocking change), it's actully acceptable to merge this.

I'll pm Senither about this, i can try to make my own pull out of this and propose that.
@chaNcharge i suggest you check if your build still fails the first time. If it no longer does, this pull would be ok to be merged. So far i didn't found any problems with building nor using it.

**Comment by chaNcharge** [comment]
I still appear to have the issue randomly, I reported it to the FredBoat devs to see if they can do anything about it.

**Comment by Macley-Kun** [comment]
https://github.com/Frederikam/FredBoat/issues/548
^ref

**Comment by Senither** [comment]
I've tried compiling Ava while using Java v11.0.1+13 and Gradle v4.10.3 on a Ubuntu 18.04.1 LTS server, both installed using [SDKMan](https://sdkman.io/) and are having no real issues at all, so the bot should compile fine, however, if Heroku only works half the time, or on second attempts, it might be better to hold off on the update to Java 11, at least until something stable comes out that works everywhere.

**Comment by Macley-Kun** [comment]
Suggest the following:
Update gradle.
Leave the Java version for heroku for what it is.
When the issue is resolved, only that little file has to be updated from 9 to 10/11.

Met vriendelijke groet,

Wesley de Vree

________________________________
Van: Alexis Tan <notifications@github.com>
Verzonden: zaterdag, december 22, 2018 9:38 PM
Aan: avaire/avaire
CC: Macley; Comment
Onderwerp: Re: [avaire/avaire] Add support for java 11 (#64)


I've tried compiling Ava while using Java v11.0.1+13 and Gradle v4.10.3 on a Ubuntu 18.04.1 LTS server, both installed using SDKMan<https://sdkman.io/> and are having no real issues at all, so the bot should compile fine, however, if Heroku only works half the time, or on second attempts, it might be better to hold off on the update to Java 11, at least until something stable comes out that works everywhere.

―

**Comment by chaNcharge** [comment]
The strange thing is that this issue sometimes happens on my local computer too. I'll keep an eye on the issue and let you know when compilation is stable.

**Comment by Macley-Kun** [comment]
Ok so, i would suggest that we update to the newer gradle,
But that we leave the heroku java version on 9 (or 10 if that also works)
then we only have to change that one value, what i suggest would be beter.

**Comment by chaNcharge** [comment]
Just tried 3 times today, doesn't seem to be causing issues anymore. I believe it is safe to pull this.

**Comment by Macley-Kun** [comment]
Update:
I'll update to JDA v4 when everything becomes a bit more stable.
Updating to v4 is a massive update since every part of the bot will be affected by it, so wanna make sure nothing actually breaks with the changes.

So this will be pulled with JDA v4 and Gradle 5 support.

**Comment by Senither** [comment]
It's a bit late, but support for Java 11 was added a while back in the form of a Gradle upgrade, the version of Gradle is different from the one defined in this PR, however, support for Java 11 exists now regardless.

**Comment by Macleykun** [comment]
Godspeed ma dude :)
Hope everything still works swell, if ya need anything just hit me up ;)

________________________________
Van: Alexis Tan <notifications@github.com>
Verzonden: Tuesday, March 2, 2021 11:03:00 PM
Aan: avaire/avaire <avaire@noreply.github.com>
Onderwerp: Re: [avaire/avaire] Add support for java 11 (#64)


Closed #64<https://github.com/avaire/avaire/pull/64>.

**Pull request closed without merging**
