### PR TITLE
Add auto updating script for heroku and forks

### PR DESCRIPTION
**Pull request by chaNcharge**
This is really useful for selfhosters as it doesn't require to set up backstroke and can be left alone for a long time. Please let me know if any changes need to be made, or if you have ideas and suggestions!

~~EDIT: The script fails to create an issue on conflict, please do not merge until I can fix this!~~

### CODE REVIEW

**Comment by chaNcharge** [comment]
Ok, now everything should be good to go. I'd appreciate it if someone else could try to replicate and test my instructions I put in the docs

**Comment by Macleykun** [comment]
Will do an extra test with this pull ;) gimmie until Friday

________________________________
Van: chaNcharge <notifications@github.com>
Verzonden: dinsdag, december 18, 2018 6:42 AM
Aan: avaire/avaire
CC: Subscribed
Onderwerp: Re: [avaire/avaire] Add auto updating script for heroku and forks (#66)


Ok, now everything should be good to go. I'd appreciate it if someone else could try to replicate and test my instructions I put in the docs

―

**Comment by Macley-Kun** [comment]
Did some testing, everything works as expected.

The only thing i want to suggest is making an option/env variable to set the branch name.

Sometimes users don't want to use master, but want to user dev instead.

Overall, it's good to go, gonna test out the other pull in abit too, so that one can get pulled asap.

**Comment by Macley-Kun** [comment]
Pull is ready for merge o7 tested this on different repo's even. No issue's what so ever.

**Review by Senither — APPROVED** [review]
Looks good, thanks again for helping out @chaNcharge, also cheers for testing it @Macley-Kun.

**Pull request merged**
